# Docker
# Build and push a Docker image to Docker Hub
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  DOCKER_REGISTRY: 'docker.io'
  DOCKER_USERNAME: '$(DOCKER_USERNAME)'
  DOCKER_PASSWORD: '$(DOCKER_PASSWORD)'
  IMAGE_NAME: 'my-app'  # Change to your image name

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(DOCKER_REGISTRY)/$(DOCKER_USERNAME)/$(IMAGE_NAME):$(tag)
        buildContext: '$(Build.SourcesDirectory)'

    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: push
        repository: '$(DOCKER_REGISTRY)/$(DOCKER_USERNAME)/$(IMAGE_NAME)'
        tags: |
          $(tag)
        containerRegistry: 'dockerhub'
      
    - script: |
        sudo chmod 777 /var/run/docker.sock
      displayName: 'Change Docker Socket Permissions'
